name: SSH connect
on: push

jobs:
  connect:
    name: SSH connect
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        env:
          PRIVATE_KEY: ${{ secrets.FUMIDAI_KEY }}
          USER_NAME: ${{ secrets.FUMIDAI_USER }}
          HOST_NAME: ${{ secrets.FUMIDAI_HOST }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ls -la
          ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -i private_key
      - name: echo
        run:
          echo "Hello, World 2"
